inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec

AllCops:
  NewCops: enable
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Style/DocumentDynamicEvalDefinition:
  Enabled: false
